### ISSUE TITLE
[Question] Why SWIMMobility and ExtendedSWIMMobility must be copied into INET

### ISSUE THREAD

**Issue by Vonfry** [ComNets-Bremen/OPS#3]
I'm sorry to ask . I am new to use omnetpp and inet. 

I want to know whether SWIMMobility and ExtendedSWIMMobility must be copied into INET and why? Because I don't want to modify the lib what I cloned. 

And I find the other files under src also use `inet` by `LD_LIBRARY_PATH` and `opp_make -I`,  I think these files are same as the above two libs.

**Comment by asangau** [comment]
> I want to know whether SWIMMobility and ExtendedSWIMMobility must be copied into INET and why? Because I don't want to modify the lib what I cloned.

Yes, they are required for the following reasons.

- SWIMMobility, if you plan to use the example .ini files
- ExtendedSWIMMobility, because the UBM models require them

Which OPS build method are you using?

- If you use the OMNeT++ IDE to build OPS, then you need to copy them into the specified INET folders and re-build INET as the README says
- If you use the command-line to build OPS, then use the bootstrap.sh script

> And I find the other files under src also use `inet` by `LD_LIBRARY_PATH` and `opp_make -I`, I think these files are same as the above two libs.

Provided that I understood your question right - some of the UBM related models and the WirelessInterface model require INET. Therefore, the code of these models have references to INET mobility code.

**Comment by Vonfry** [comment]
Thank for your replying.

> Yes, they are required for the following reasons.
> 
> * SWIMMobility, if you plan to use the example .ini files
> * ExtendedSWIMMobility, because the UBM models require them

I see that. I want to know could we put these file under `<OPS>/src` instead copying them to INET? Are there any restrict to do this except include path in `<OPS>/src` and package name?

**Comment by asangau** [comment]
Thanks for your thoughts. 

There is no restriction to changing references to make these models completely part of OPS.

But, the intension is to make these models a part of INET. From our last discussions with the INET developers, we agreed to make the Github pull requests to include these in a future INET release. Unfortunately, we haven't come around to actually doing that. Until then, we will keep it as it is in OPS and, completely remove them from OPS, when done.
